development:
  adapter: postgresql
  encoding: unicode
  database: brandometer_development
  pool: 5
  username: Joel
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: brandometer_test
  pool: 5
  username: Joel
  password:
